spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/SDMLabRevision
    username: SDM_Manager
    password: SDM_PASSWORD
mybatis:
  type-aliases-package: org.SDM.**.entity
  mapper-locations: org.SDM.**.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl